# This YAML file shows how to deploy the snapshot controller

---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: snapshot-controller
spec:
  serviceName: "snapshot-controller"
  replicas: 1
  selector:
    matchLabels:
      app: snapshot-controller
  template:
    metadata:
      labels:
        app: snapshot-controller
    spec:
      serviceAccount: snapshot-controller
      containers:
        - name: snapshot-controller
          image: k8s.gcr.io/sig-storage/snapshot-controller:v2.1.1


          args:
            - "--v=5"
            - "--leader-election=false"
          imagePullPolicy: Always
